name: alkitab_2_0
description: A Malay Bible app with Supabase authentication

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  supabase_flutter: ^2.8.4
  flutter_dotenv: ^5.1.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  flutter_riverpod: ^2.4.9
  go_router: ^14.8.1
  connectivity_plus: ^6.1.3
  flutter_svg: ^2.0.9
  intl: ^0.20.2
  shared_preferences: ^2.2.2
  http: ^1.3.0
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  share_plus: ^10.1.4
  flutter_speed_dial: ^7.0.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  hive_generator: ^2.0.1
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/bibles/
    - assets/fonts/

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic
