name: alkitab_2_0
description: Alkitab 2.0 - Modern Malay Bible App with offline reading, bookmarks, notes, highlighting, and cloud sync

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none'

version: 1.1.0+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # UI and Icons
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.9
  flutter_speed_dial: ^7.0.0
  shimmer: ^3.0.0

  # State Management and Routing
  flutter_riverpod: ^2.5.1
  go_router: ^16.2.1

  # Backend and Authentication
  supabase_flutter: ^2.8.4
  
  # Local Storage and Preferences
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  shared_preferences: ^2.5.3

  # Networking and Connectivity
  connectivity_plus: ^7.0.0
  http: ^1.3.0

  # Internationalization
  intl: ^0.20.2

  # Media and Sharing
  image_picker: ^1.1.2
  flutter_image_compress: ^2.4.0
  share_plus: ^12.0.0
  flutter_tts: ^4.2.2

  # Environment Configuration
  flutter_dotenv: ^6.0.0
  uuid: ^4.5.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

  # Code Generation
  hive_generator: ^2.0.1
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/images/
    - assets/fonts/
    - assets/icon/
    - assets/bibles/indo_tb.json
    - assets/bibles/indo_tm.json

  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Italic.ttf
          style: italic

# App Icon Configuration
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  remove_alpha_ios: true
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FAF9F6"
    theme_color: "#8B4513"
  windows:
    generate: true
    image_path: "assets/icon/icon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon/icon.png"