// lib/constants/bible_data.dart

const Map<String, int> bookIndexMap = {
  'genesis': 1,
  'exodus': 2,
  'leviticus': 3,
  'numbers': 4,
  'deuteronomy': 5,
  'joshua': 6,
  'judges': 7,
  'ruth': 8,
  '1_samuel': 9,
  '2_samuel': 10,
  '1_kings': 11,
  '2_kings': 12,
  '1_chronicles': 13,
  '2_chronicles': 14,
  'ezra': 15,
  'nehemiah': 16,
  'esther': 17,
  'job': 18,
  'psalms': 19,
  'proverbs': 20,
  'ecclesiastes': 21,
  'song_of_solomon': 22,
  'isaiah': 23,
  'jeremiah': 24,
  'lamentations': 25,
  'ezekiel': 26,
  'daniel': 27,
  'hosea': 28,
  'joel': 29,
  'amos': 30,
  'obadiah': 31,
  'jonah': 32,
  'micah': 33,
  'nahum': 34,
  'habakkuk': 35,
  'zephaniah': 36,
  'haggai': 37,
  'zechariah': 38,
  'malachi': 39,
  'matt': 40,
  'mark': 41,
  'luke': 42,
  'john': 43,
  'acts': 44,
  'romans': 45,
  '1_corinthians': 46,
  '2_corinthians': 47,
  'galatians': 48,
  'ephesians': 49,
  'philippians': 50,
  'colossians': 51,
  '1_thessalonians': 52,
  '2_thessalonians': 53,
  '1_timothy': 54,
  '2_timothy': 55,
  'titus': 56,
  'philemon': 57,
  'hebrews': 58,
  'james': 59,
  '1_peter': 60,
  '2_peter': 61,
  '1_john': 62,
  '2_john': 63,
  '3_john': 64,
  'jude': 65,
  'revelation': 66,
};

const Map<String, String> bookNameMap = {
  'genesis': 'Kejadian',
  'exodus': 'Keluaran',
  'leviticus': 'Imamat',
  'numbers': 'Bilangan',
  'deuteronomy': 'Ulangan',
  'joshua': 'Yosua',
  'judges': 'Hakim-Hakim',
  'ruth': 'Rut',
  '1_samuel': '1 Samuel',
  '2_samuel': '2 Samuel',
  '1_kings': '1 Raja-Raja',
  '2_kings': '2 Raja-Raja',
  '1_chronicles': '1 Tawarikh',
  '2_chronicles': '2 Tawarikh',
  'ezra': 'Ezra',
  'nehemiah': 'Nehemia',
  'esther': 'Ester',
  'job': 'Ayub',
  'psalms': 'Mazmur',
  'proverbs': 'Amsal',
  'ecclesiastes': 'Pengkhotbah',
  'song_of_solomon': 'Kidung Agung',
  'isaiah': 'Yesaya',
  'jeremiah': 'Yeremia',
  'lamentations': 'Ratapan',
  'ezekiel': 'Yehezkiel',
  'daniel': 'Daniel',
  'hosea': 'Hosea',
  'joel': 'Yoel',
  'amos': 'Amos',
  'obadiah': 'Obaja',
  'jonah': 'Yunus',
  'micah': 'Mikha',
  'nahum': 'Nahum',
  'habakkuk': 'Habakuk',
  'zephaniah': 'Zefanya',
  'haggai': 'Hagai',
  'zechariah': 'Zakharia',
  'malachi': 'Maleakhi',
  'matt': 'Matius',
  'mark': 'Markus',
  'luke': 'Lukas',
  'john': 'Yohanes',
  'acts': 'Kisah Para Rasul',
  'romans': 'Roma',
  '1_corinthians': '1 Korintus',
  '2_corinthians': '2 Korintus',
  'galatians': 'Galatia',
  'ephesians': 'Efesus',
  'philippians': 'Filipi',
  'colossians': 'Kolose',
  '1_thessalonians': '1 Tesalonika',
  '2_thessalonians': '2 Tesalonika',
  '1_timothy': '1 Timotius',
  '2_timothy': '2 Timotius',
  'titus': 'Titus',
  'philemon': 'Filemon',
  'hebrews': 'Ibrani',
  'james': 'Yakobus',
  '1_peter': '1 Petrus',
  '2_peter': '2 Petrus',
  '1_john': '1 Yohanes',
  '2_john': '2 Yohanes',
  '3_john': '3 Yohanes',
  'jude': 'Yudas',
  'revelation': 'Wahyu',
};

const Map<String, int> chapterCountMap = {
  'genesis': 50,
  'exodus': 40,
  'leviticus': 27,
  'numbers': 36,
  'deuteronomy': 34,
  'joshua': 24,
  'judges': 21,
  'ruth': 4,
  '1_samuel': 31,
  '2_samuel': 24,
  '1_kings': 22,
  '2_kings': 25,
  '1_chronicles': 29,
  '2_chronicles': 36,
  'ezra': 10,
  'nehemiah': 13,
  'esther': 10,
  'job': 42,
  'psalms': 150,
  'proverbs': 31,
  'ecclesiastes': 12,
  'song_of_solomon': 8,
  'isaiah': 66,
  'jeremiah': 52,
  'lamentations': 5,
  'ezekiel': 48,
  'daniel': 12,
  'hosea': 14,
  'joel': 3,
  'amos': 9,
  'obadiah': 1,
  'jonah': 4,
  'micah': 7,
  'nahum': 3,
  'habakkuk': 3,
  'zephaniah': 3,
  'haggai': 2,
  'zechariah': 14,
  'malachi': 4,
  'matt': 28,
  'mark': 16,
  'luke': 24,
  'john': 21,
  'acts': 28,
  'romans': 16,
  '1_corinthians': 16,
  '2_corinthians': 13,
  'galatians': 6,
  'ephesians': 6,
  'philippians': 4,
  'colossians': 4,
  '1_thessalonians': 5,
  '2_thessalonians': 3,
  '1_timothy': 6,
  '2_timothy': 4,
  'titus': 3,
  'philemon': 1,
  'hebrews': 13,
  'james': 5,
  '1_peter': 5,
  '2_peter': 3,
  '1_john': 5,
  '2_john': 1,
  '3_john': 1,
  'jude': 1,
  'revelation': 22,
};

int getBookIndex(String bookId) => bookIndexMap[bookId] ?? 1;
int getMaxChapters(String bookId) => chapterCountMap[bookId] ?? 1;
String getBookName(String bookId) => bookNameMap[bookId] ?? bookId;
