// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBnv1IXpKdsNlrNCjc2sxDZSaeHak_mzYk',
    appId: '1:816180259014:web:a09e850bf8f00af1c58fc7',
    messagingSenderId: '816180259014',
    projectId: 'alkitab-2-0',
    authDomain: 'alkitab-2-0.firebaseapp.com',
    storageBucket: 'alkitab-2-0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnv1IXpKdsNlrNCjc2sxDZSaeHak_mzYk',
    appId: '1:816180259014:android:a09e850bf8f00af1c58fc7',
    messagingSenderId: '816180259014',
    projectId: 'alkitab-2-0',
    storageBucket: 'alkitab-2-0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnv1IXpKdsNlrNCjc2sxDZSaeHak_mzYk',
    appId: '1:816180259014:ios:a09e850bf8f00af1c58fc7',
    messagingSenderId: '816180259014',
    projectId: 'alkitab-2-0',
    storageBucket: 'alkitab-2-0.firebasestorage.app',
    iosBundleId: 'com.haweeinc.alkitab',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnv1IXpKdsNlrNCjc2sxDZSaeHak_mzYk',
    appId: '1:816180259014:macos:a09e850bf8f00af1c58fc7',
    messagingSenderId: '816180259014',
    projectId: 'alkitab-2-0',
    storageBucket: 'alkitab-2-0.firebasestorage.app',
    iosBundleId: 'com.haweeinc.alkitab',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBnv1IXpKdsNlrNCjc2sxDZSaeHak_mzYk',
    appId: '1:816180259014:windows:a09e850bf8f00af1c58fc7',
    messagingSenderId: '816180259014',
    projectId: 'alkitab-2-0',
  );
}